name: CI + CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  BuildJob:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    env:
      CONTENT: World!
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: EchoSecret
        run: echo Secret is ${{ secrets.day }}

      - name: EchoEnvVar
        run: echo Hello, $CONTENT

  # DeployDev:
  #   name: Deploy to Dev 
  #   if: github.event_name == 'push'
  #   needs: [BuildJob]
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: Dev
  #   steps:
  #     - name: Deploy
  #       run: echo I ${{ env.day }}