name: CI + CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  BuildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: EchoSomething
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
   # needs: [BuildJob]
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Deploy
        run: echo I am deploying!