name: CI + CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  BuildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: EchoSomething
        run: echo Hello, world!